# ruff: noqa: E501
"""Freeze the human-adjudicated gold set from my (Fable) labels.

Each label is my own judgment reading the mission text, applying one rule
consistently: a religion label requires that religion's word/identity to
appear in the mission TEXT (not merely the org name). Name-only religious
signal -> secular/unknown + flag. Liberally flagged: culture/advocacy orgs
of a faith community, faith-affiliated-but-secular-mission institutions,
thin text, and interfaith/academic edge cases -> flagged for human audit.
"""

from __future__ import annotations

import json
from pathlib import Path

CODE = {
    "EP": "evangelical_protestant", "CA": "catholic", "OC": "orthodox_christian",
    "CU": "christian_unspecified", "CS": "christian_science", "ML": "mormon_lds",
    "JW": "jewish", "MU": "muslim", "OR": "other_religion", "SE": "secular",
    "UN": "unknown",
}
# index: (code, flagged, reason quoting/paraphrasing the deciding text)
LABELS: dict[int, tuple[str, int, str]] = {
    0: ("CU", 0, "'carries out the healing work of Christ'"),
    1: ("EP", 0, "'scripturally based discipleship... biblical worldview'"),
    2: ("EP", 0, "'come to Christ... more like our precious Lord and Savior Jesus Christ'"),
    3: ("EP", 0, "'supremacy of God in all things... through Jesus Christ'"),
    4: ("EP", 0, "'biblical instruction, character development'"),
    5: ("CA", 0, "'Catholic Charities... grounded in the life and ministry of Jesus Christ'"),
    6: ("CA", 0, "'carry out Christ's healing ministry... Catholic Medical Center'"),
    7: ("EP", 0, "'spreading the Good News of Jesus Christ'"),
    8: ("EP", 0, "'accomplishing the Great Commission... hope of the Gospel'"),
    9: ("CU", 0, "'through the love of Jesus Christ'"),
    10: ("CU", 1, "'Missionary medical and dental... mission fields' — only missionary language; could be secular medical mission"),
    11: ("CU", 1, "'public understanding of Biblical writings' — academic biblical scholarship, ambiguous"),
    12: ("CU", 0, "'Motivated by Christ-like love'"),
    13: ("EP", 0, "'help children fall deeply in love with Jesus'"),
    14: ("CU", 0, "'Empowered by the active grace of Christ'"),
    15: ("EP", 0, "'trust Him as Lord and Savior... share Him with others'"),
    16: ("CA", 0, "'a ministry of the Roman Catholic Church'"),
    17: ("CA", 0, "'Christ's healing mission... the Catholic Church... Catholic health care'"),
    18: ("CU", 0, "'modeling Christ-centered values'"),
    19: ("CA", 0, "'the Catholic Church expressed in Catholic health care'"),
    20: ("CA", 0, "'the Catholic Church expressed in Catholic health care'"),
    21: ("CU", 0, "'impact their communities through Christ'"),
    22: ("CU", 0, "'following Christ's teaching to love our neighbors'"),
    23: ("CU", 0, "'the power & love of Jesus Christ'"),
    24: ("EP", 0, "'Christian & Missionary Alliance... whole gospel to the whole world'"),
    25: ("EP", 0, "'the command of Christ to evangelize and make disciples'"),
    26: ("EP", 0, "'according to biblical principles'"),
    27: ("CU", 0, "'explore the relevance of the christian faith'"),
    28: ("EP", 0, "'evangelization and discipleship... the Church of Jesus Christ'"),
    29: ("CU", 1, "'Guided by Biblical teaching... care for God's creation' — possibly interfaith"),
    30: ("EP", 0, "'sharing the Gospel of Jesus Christ in word and deed'"),
    31: ("EP", 0, "'the life-changing word of Christ... Christian Discipleship'"),
    32: ("EP", 0, "'competent in biblical truth and diligent in making disciples'"),
    33: ("CU", 0, "'sharing the love of Christ'"),
    34: ("EP", 0, "'biblical and historic Christian faith... ministry to the Church'"),
    35: ("CU", 0, "'the historic Christian faith... faithful Christian living'"),
    36: ("EP", 0, "'Spread the Gospel through evangelistic outreach & establishment of churches'"),
    37: ("EP", 0, "'train... pastors and evangelists'"),
    38: ("EP", 0, "'spread the Gospel of Jesus Christ'"),
    39: ("CA", 1, "'As the Sisters of Mercy... the healing ministry of Jesus' — Catholic order"),
    40: ("EP", 0, "'accelerate the great commission... least reached peoples'"),
    41: ("CU", 1, "'partner with churches to share... life in Christ'"),
    42: ("CU", 0, "'a beautiful Christ-centered community'"),
    43: ("CU", 0, "'share the transforming love of Christ'"),
    44: ("CA", 0, "'Third Order Dominicans devoted to preserving traditional Catholic faith'"),
    45: ("SE", 1, "'State-wide social service agency' — no religious word in text (Catholic only in name)"),
    46: ("CU", 1, "'a Christian voluntary organization' — SVdP is Catholic but text says Christian"),
    47: ("CA", 0, "'A Catholic, Benedictine college'"),
    48: ("CA", 0, "'a Catholic coeducational institution... Sisters of the Presentation of Mary'"),
    49: ("CA", 0, "'provides a Catholic... education'"),
    50: ("CA", 0, "'a Roman Catholic institution of higher learning'"),
    51: ("CA", 0, "'in the light of the Catholic faith'"),
    52: ("CA", 0, "'the traditions and faith of the Roman Catholic Church'"),
    53: ("CA", 0, "'a Catholic, co-ed, college-prep school'"),
    54: ("CA", 0, "'a private, Jesuit, Catholic, liberal arts college'"),
    55: ("CA", 0, "'a comprehensive, Catholic Augustinian institution'"),
    56: ("CA", 0, "'a Catholic institution... founded by the Congregation of Holy Cross'"),
    57: ("SE", 1, "'prepare young students... for success' — no religious word (Newman only in name)"),
    58: ("CA", 0, "'scholarships to students in schools in the Fall River Diocese'"),
    59: ("CA", 0, "'a Catholic liberal arts and sciences college'"),
    60: ("SE", 1, "'skilled nursing... for the frail and the elderly' — no religious word (Catholic in name)"),
    61: ("CA", 0, "'the Catholic identity of the College... Judaeo-Christian principles'"),
    62: ("SE", 1, "'educate a diverse group of students' — no religious word (Our Lady in name)"),
    63: ("CA", 0, "'Catholic Charities' mission is to welcome and serve'"),
    64: ("CA", 0, "'a Catholic college preparatory school'"),
    65: ("CA", 0, "'a Jesuit middle school'"),
    66: ("CA", 0, "'advance the ministries and programs of the Archdiocese of Boston'"),
    67: ("CU", 1, "'a ministry of the Episcopal Diocese of Honduras' — Episcopal/Anglican; unspecified to avoid evangelical mislabel"),
    68: ("CA", 0, "'Catholic Charities of the Archdiocese of Miami'"),
    69: ("CA", 0, "'education in the Catholic tradition'"),
    70: ("SE", 1, "'a thrift store and food pantry' — no religious word (St Vincent de Paul in name)"),
    71: ("CA", 0, "'a Catholic, Dominican, liberal arts institution'"),
    72: ("CA", 0, "'a Catholic institution founded by the Sisters of Mercy'"),
    73: ("CA", 0, "'put faith into action' + Catholic Charities"),
    74: ("CA", 0, "'leadership in Catholic higher education'"),
    75: ("CA", 0, "'promote the Roman Catholic Church in China'"),
    76: ("CA", 0, "'a Catholic, Vincentian... institution'"),
    77: ("CA", 0, "'a Catholic university... in the Dominican tradition'"),
    78: ("CA", 0, "'Catholic Charities Neighborhood Services provides...'"),
    79: ("CA", 0, "'the Roman Catholic Diocese of Brooklyn... the life of the Church'"),
    80: ("CA", 0, "'Catholic and ecumenical... the Sisters of Charity'"),
    81: ("CA", 0, "'in the Jesuit tradition'"),
    82: ("CA", 0, "'an independent Catholic institution... the Dominican tradition'"),
    83: ("CA", 0, "'apostolic initiatives... the Catholic Prelature of Opus Dei'"),
    84: ("CA", 0, "'a Catholic university... the tradition of the Christian Brothers'"),
    85: ("CA", 0, "'supported by the catholic church... the pope and the holy see'"),
    86: ("SE", 1, "'transforming the lives of those in need' — no religious word (Episcopal in name)"),
    87: ("CA", 0, "'outstanding Catholic elementary schools'"),
    88: ("CA", 0, "'Holy Family Cristo Rey Catholic High School'"),
    89: ("CA", 0, "'non-Catholics and Catholics alike' + Catholic Charities"),
    90: ("JW", 1, "'Jewish-themed and multicultural programming, films' — cultural"),
    91: ("JW", 0, "'Jewish philanthropic, benevolent, educational, and communal activities'"),
    92: ("JW", 1, "'charitable services in the United States and Israel' — Israel + name only"),
    93: ("JW", 0, "'life-enhancing study of Jewish texts and ideas'"),
    94: ("JW", 0, "'Jewish life in Colorado, Israel'"),
    95: ("JW", 0, "'religious... purposes of Jewish Comm Federation of SF'"),
    96: ("JW", 0, "'Orthodox women who model a dynamic Judaism'"),
    97: ("JW", 0, "'a synagogue for the Jewish community... religious precepts'"),
    98: ("JW", 0, "'Greater Boston's Jewish Federation... our Jewish values'"),
    99: ("JW", 1, "'guided by Jewish values and traditions' — nursing home"),
    100: ("JW", 0, "'excellence in Jewish learning & leadership'"),
    101: ("JW", 0, "'the organized Jewish community'"),
    102: ("JW", 0, "'guided by Jewish values'"),
    103: ("JW", 0, "'guided by Jewish traditions of social responsibility'"),
    104: ("SE", 1, "'find employment and build careers' — no Jewish word in text (Jewish in name)"),
    105: ("JW", 0, "'the central Jewish communal organization... Jewish life'"),
    106: ("JW", 0, "'religious and secular education' at a Hebrew academy"),
    107: ("JW", 0, "'nurtures and sustains the Jewish community... Israel'"),
    108: ("JW", 1, "'Yiddish and modern Jewish literature and culture' — cultural"),
    109: ("SE", 1, "'vital social, health & community services' — no Jewish word in text (Jewish in name)"),
    110: ("JW", 1, "'films... relevant to the Jewish experience' — cultural"),
    111: ("JW", 0, "'Advanced Jewish Education'"),
    112: ("JW", 0, "'a lifelong love of Jewish traditions, values, and community'"),
    113: ("JW", 0, "'advance Jewish study for women'"),
    114: ("JW", 0, "'a premier Jewish education... Jewish values, texts'"),
    115: ("UN", 1, "'See Schedule O' — uninformative (Jewish in name)"),
    116: ("SE", 1, "'Education of students grades K-8' — no Jewish word in text (Jewish Day School in name)"),
    117: ("JW", 0, "'engage in Jewish life and make Jewish choices'"),
    118: ("JW", 1, "'equips Jewish leaders... to advocate for justice' — advocacy"),
    119: ("JW", 0, "'Jewish religious, charitable and educational purposes... Yeshivat'"),
    120: ("JW", 1, "'the Maltz Museum of Jewish Heritage' — thin ('diversity and tolerance')"),
    121: ("JW", 0, "'traditional Torah-true Judaism'"),
    122: ("JW", 0, "'providing Jewish boys... our culture and traditions'"),
    123: ("JW", 0, "'support primarily Jewish educational institutions'"),
    124: ("JW", 0, "'preserving Touro Synagogue... colonial Jewish history'"),
    125: ("JW", 0, "'enrich the lives of Jewish students... the Jewish people'"),
    126: ("JW", 0, "'the Jewish community of Greater New Haven'"),
    127: ("JW", 0, "'welcome all Jewish families... Jewish education'"),
    128: ("JW", 0, "'a Jewish non-profit overnight camp... the Jewish community'"),
    129: ("SE", 1, "'non-profit health care facility... skilled nursing' — no Jewish word in text (Jewish Home in name)"),
    130: ("JW", 0, "'safeguarding our Jewish community... Israel... Jewish life'"),
    131: ("SE", 1, "'individuals and families of all backgrounds... social services' — no Jewish word in text"),
    132: ("JW", 1, "'the New Haven Jewish Community Council Housing Corporation'"),
    133: ("JW", 0, "'support for local and global Jewish community'"),
    134: ("SE", 1, "'financial assistance to charitable health care initiatives' — no Jewish word in text"),
    135: ("MU", 1, "'civil rights education to Muslims' — advocacy"),
    136: ("SE", 1, "'a healthy, educated, sustainable community... relief' — no Islamic word in text"),
    137: ("MU", 0, "'Establish mosque used by... Muslims for prayers... Koran'"),
    138: ("SE", 1, "'domestic violence support services' — no Islamic word in text (Muslim in name)"),
    139: ("MU", 0, "'Islamic and cultural services to local Muslims'"),
    140: ("MU", 1, "'support American Muslim storytelling' — media/representation"),
    141: ("MU", 1, "'human rights in Muslim societies' — advocacy"),
    142: ("MU", 1, "'mobilizes Muslim American voters' — advocacy"),
    143: ("MU", 1, "'Help India's muslims and minorities' — relief/advocacy"),
    144: ("MU", 0, "'MOSQUE'"),
    145: ("MU", 1, "'sexual health... awareness in Muslim communities'"),
    146: ("OR", 1, "'Christian/Muslim dialogue... Center of Muslim and Christian Studies' — interfaith"),
    147: ("UN", 1, "'See Part III, Line 1' — uninformative (Muslim in name)"),
    148: ("SE", 1, "'predominately Muslim societies' — regional descriptor, not the org's religious purpose"),
    149: ("MU", 0, "'the teachings of the Holy Quran and traditions of Prophet Muhammad'"),
    150: ("MU", 0, "'grounded in the Islamic scholarly traditions'"),
    151: ("SE", 1, "'health, wellness... in the inner-city' — no Islamic word in text (Muslim in name)"),
    152: ("SE", 1, "'Promote civil liberties' — no Islamic word in text (Muslim in name)"),
    153: ("SE", 1, "'Southwest Asian and North African artists' — Arab/Muslim arts, cultural not religious"),
    154: ("MU", 1, "'enhance understanding of Islam... empower American Muslims' — advocacy"),
    155: ("MU", 1, "'materials related to the Arab and Muslim world' — cultural"),
    156: ("MU", 0, "'leaders and scholars grounded in the Islamic tradition'"),
    157: ("SE", 1, "'advocacy for human and civil rights' — no Islamic word in text (Muslim in name)"),
    158: ("MU", 1, "'Founded on Islamic principles... empowers women experiencing domestic abuse'"),
    159: ("MU", 1, "'enhance the understanding of Islam... empower American Muslims' — advocacy"),
    160: ("MU", 0, "'a common place of worship and religious education... a mosque'"),
    161: ("MU", 0, "'a place to worship and a burial place' (Islamic Center)"),
    162: ("MU", 0, "'an Islamic cultural environment'"),
    163: ("MU", 1, "'enhances the understanding of Islam... empowers American Muslims' — advocacy"),
    164: ("MU", 1, "'foster understanding of Muslims' — education about Islam"),
    165: ("MU", 1, "'enhance understanding of Islam... empower American Muslims' — advocacy"),
    166: ("MU", 0, "'a progressive Islamic environment... devotion to God'"),
    167: ("MU", 1, "'the voice and power of Muslim women'"),
    168: ("MU", 1, "'civic participation among Muslims... voter engagement' — advocacy"),
    169: ("MU", 0, "'pioneer Islamic research'"),
    170: ("SE", 1, "'a facility for youth education, enrichment' — no Islamic word in text (Muslim in name)"),
    171: ("MU", 0, "'serve our community as an Islamic mosque'"),
    172: ("MU", 1, "'knowledge of the rich history of Islamic medicine'"),
    173: ("MU", 0, "'Islamic rituals and education'"),
    174: ("MU", 0, "'empower the youth with the Islamic identity'"),
    175: ("MU", 0, "'practice and share the values of Islam... religious... facilities'"),
    176: ("SE", 1, "'relief and development... regardless of gender, race, or religion' — no Islamic-practice word in text (Islamic in name)"),
    177: ("UN", 1, "'See Schedule O' — uninformative (Muslim in name)"),
    178: ("SE", 0, "'Community hospital committed to wellness... holistic healing' — St Joseph in name, secular by text"),
    179: ("SE", 0, "'a high-performing, public charter school'"),
    180: ("SE", 0, "'a fully residential academic community... service to the greater good'"),
    181: ("CU", 0, "'a quality Christian education'"),
    182: ("UN", 1, "'See Schedule O' — uninformative (Baptist in name)"),
    183: ("SE", 1, "'lives of leadership and service... academic and spiritual' — no explicit faith"),
    184: ("CU", 0, "'educate with a Christian worldview'"),
    185: ("SE", 0, "'developing to the fullest extent... their particular gifts'"),
    186: ("CU", 1, "'Our Episcopal heritage guides our moral and ethical values'"),
    187: ("SE", 0, "'develop courageous learners and caring citizens'"),
    188: ("SE", 0, "'a rigorous liberal arts & professional education' — Saint Joseph in name"),
    189: ("SE", 0, "'excellence in liberal arts education'"),
    190: ("SE", 1, "'elementary and secondary education' — no religious word (Christian Heritage in name)"),
    191: ("SE", 0, "'support for related tax exempt hospitals'"),
    192: ("SE", 0, "'an independent, coeducational institution'"),
    193: ("SE", 0, "'an affordable liberal arts education'"),
    194: ("UN", 1, "'See Schedule O' — uninformative (St Ann's in name)"),
    195: ("SE", 1, "'education... rooted in intellectual excellence and ethical virtue' — no explicit faith (Grace Church in name)"),
    196: ("UN", 1, "'See Schedule O' — uninformative"),
    197: ("SE", 0, "'the educational needs of boys pre-K through 8'"),
    198: ("SE", 0, "'improving the health of our community'"),
    199: ("SE", 0, "'comprehensive medical and nursing care'"),
    200: ("SE", 0, "'palliative care for terminally ill cancer patients' — Calvary in name"),
    201: ("SE", 0, "'post secondary educational services'"),
    202: ("SE", 0, "'the health care needs of the NY community'"),
    203: ("SE", 0, "'raise public funds to support Calvary Hospital'"),
    204: ("SE", 0, "'world class patient care, teaching, research'"),
    205: ("SE", 0, "'support activities... for the benefit of the Hospital'"),
    206: ("SE", 0, "'education to approximately 1,000 students' — Trinity Episcopal in name"),
    207: ("SE", 0, "'higher educational opportunities' — Saint Rose in name"),
    208: ("SE", 0, "'exceptional healthcare'"),
    209: ("SE", 0, "'health care and hospital services'"),
    210: ("SE", 0, "'a liberal arts education... leadership and service' — Mount Saint Mary in name"),
    211: ("SE", 0, "'an independent boys college preparatory school'"),
    212: ("SE", 0, "'fundraising... for affiliate St Mary's Medical Center'"),
    213: ("SE", 0, "'undergraduate education in liberal arts'"),
    214: ("SE", 0, "'health care and hospital services'"),
    215: ("CU", 0, "'provide a Christian school in the local community'"),
    216: ("CU", 1, "'Adventist Health St. Helena' — Seventh-day Adventist affiliation"),
    217: ("CU", 1, "'owned by the Washington Conference of Seventh-day Adventists'"),
    218: ("CU", 0, "'graduate Christian leaders who... impact their world for the King of Kings'"),
    219: ("CU", 0, "'superior Christian education'"),
    220: ("CU", 0, "'Christian education for grades K through 12'"),
    221: ("SE", 1, "'a model health system... extraordinary care' — no religious word (Lutheran in name)"),
    222: ("CU", 0, "'Christian school'"),
    223: ("SE", 0, "'discovering basic mechanisms of regeneration and aging' — research"),
    224: ("UN", 1, "'Education' — single word, uninformative"),
    225: ("SE", 0, "'Operating a summer camp'"),
    226: ("SE", 0, "'Secondary school education'"),
    227: ("SE", 0, "'Community Hospital'"),
    228: ("SE", 0, "'PUBLIC LIBRARY'"),
    229: ("SE", 0, "'Critical Access Hospital'"),
    230: ("SE", 0, "'Educational Institution'"),
    231: ("SE", 0, "'Museum/Educational'"),
    232: ("SE", 0, "'PROVIDE SHELTER TO HOMELESS'"),
    233: ("SE", 0, "'conserve, restore... land and water resources'"),
    234: ("SE", 0, "'protect and conserve land'"),
    235: ("SE", 0, "'conserve and steward the natural and historical resources'"),
    236: ("SE", 0, "'LAND CONSERVATION'"),
    237: ("SE", 0, "'ARTS EXPERIENCES FOR ALL'"),
    238: ("UN", 1, "'See Schedule O' — uninformative"),
    239: ("SE", 0, "'CONSERVATION OF PRIVATE LAND'"),
    240: ("SE", 0, "'HOMELESS SHELTER'"),
    241: ("UN", 1, "'See Part III, Line 1' — uninformative"),
    242: ("SE", 1, "'contemplative methods for the benefit of civil society' — spiritual-but-secular"),
    243: ("SE", 0, "'EDUCATION OF CHILDREN'"),
    244: ("SE", 0, "'SUPPORT OAKLAND CA ARTISTS'"),
    245: ("UN", 1, "'SEE SCHEDULE O.' — uninformative"),
    246: ("SE", 0, "'SUPPORT FOR THE LGBTQ+ COMMUNITY'"),
    247: ("UN", 1, "'SEE SCHEDULE O' — uninformative"),
    248: ("UN", 1, "'SEE SCHEDULE O' — uninformative"),
    249: ("SE", 0, "'Fundraising and endowment management for the University of Maine'"),
    250: ("SE", 0, "'conservation and preservation of native ecosystems'"),
    251: ("SE", 0, "'Critical Access Hospital'"),
    252: ("SE", 0, "'Institute of Higher Learning'"),
    253: ("SE", 0, "'SECONDARY EDUCATION'"),
    254: ("UN", 1, "'SEE SCHEDULE O.' — uninformative"),
    255: ("SE", 0, "'Critical Access Hospital'"),
    256: ("SE", 0, "'EDUCATION'"),
    257: ("SE", 0, "'LAND CONSERVATION'"),
    258: ("SE", 0, "'building the endowment for the... University of New Hampshire'"),
    259: ("SE", 0, "'Federally Qualified Health Center'"),
    260: ("UN", 1, "'SEE SCHEDULE O.' — uninformative (International Missions in name)"),
    261: ("UN", 1, "'SEE SCHEDULE O' — uninformative (Gandhi Museum in name)"),
    262: ("UN", 1, "'SEE PART III, LINE 1.' — uninformative"),
    263: ("SE", 0, "'supporting the charitable purposes of the Nobel Foundation'"),
    264: ("UN", 1, "'SEE SCHEDULE O' — uninformative"),
    265: ("SE", 0, "'CONSERVATION OF FARM AND FOREST LANDS'"),
    266: ("SE", 0, "'STRENGTHEN COMMUNITY FOOD SYSTEMS'"),
    267: ("SE", 0, "'Education and mentoring'"),
    268: ("SE", 0, "'powerful, enriching and diverse musical experiences'"),
    269: ("SE", 0, "'help people who are visually impaired or blind'"),
    270: ("SE", 0, "'Preserve and maintain the Victoria Mansion'"),
    271: ("SE", 0, "'mobilizing the caring power of people... essential services'"),
    272: ("SE", 0, "'Independent secondary school'"),
    273: ("SE", 0, "'School providing services to children in need'"),
    274: ("SE", 0, "'creative, courageous and resilient... lives of fulfillment'"),
    275: ("SE", 0, "'high quality housing and services to those 60+'"),
    276: ("SE", 0, "'discover precise genomic solutions for disease'"),
    277: ("SE", 0, "'LONG-TERM CARE FOR THE SICK AND ELDERLY'"),
    278: ("SE", 0, "'Preserve and share Maine's story'"),
    279: ("SE", 0, "'educate students in mind, body, and spirit' — generic 'spirit'"),
    280: ("SE", 0, "'inspire and enable all young people... full potential'"),
    281: ("SE", 0, "'to care for one another'"),
    282: ("SE", 0, "'engages the imagination and intellect of its students'"),
    283: ("SE", 0, "'eliminate racism and empower women' — YWCA, secular text"),
    284: ("SE", 0, "'understanding of... Wabanaki Nations heritage'"),
    285: ("SE", 0, "'undergraduate study in the traditional disciplines of the liberal arts'"),
    286: ("SE", 0, "'Critical access hospital'"),
    287: ("SE", 0, "'skilled nursing and other in-home healthcare services'"),
    288: ("SE", 0, "'treat a wide range of psychiatric, emotional... issues'"),
    289: ("SE", 0, "'improve the health of people, communities'"),
    290: ("SE", 0, "'youth development, healthy living' — YMCA, secular text"),
    291: ("SE", 0, "'Provide health services to the Camden Area community'"),
    292: ("SE", 0, "'children and adults with disabilities... better lives'"),
    293: ("SE", 0, "'advance animal welfare'"),
    294: ("SE", 0, "'living options, high-quality health services... older adults'"),
    295: ("SE", 0, "'a four-year private undergraduate liberal arts college'"),
    296: ("SE", 0, "'shelter and adoption services for unwanted animals'"),
    297: ("SE", 0, "'strengthen Downeast Maine coastal and island communities' — Mission in name, secular text"),
    298: ("SE", 0, "'earn a high school diploma'"),
    299: ("SE", 0, "'grow in skills and scholarship, serve others'"),
    300: ("SE", 0, "'information, enlightenment... the life of the mind'"),
    301: ("SE", 0, "'senior living options... dignity, safety'"),
    302: ("SE", 0, "'prepare for the rigors of college'"),
    303: ("SE", 0, "'promoting virtue and useful knowledge'"),
    304: ("SE", 0, "'the ideals of life-long learning' — library"),
    305: ("SE", 0, "'reach their highest potential in mind, body and spirit' — generic"),
    306: ("SE", 0, "'a not-for-profit community and referral system of hospitals'"),
    307: ("SE", 0, "'the enjoyment of life-long learning' — library"),
    308: ("SE", 0, "'education, financial stability, and health'"),
    309: ("SE", 0, "'teach fine craftsmanship'"),
    310: ("SE", 0, "'an independent high school'"),
    311: ("SE", 0, "'conserve Maine's wildlife and wildlife habitat'"),
    312: ("SE", 0, "'prepares students for success... leadership and service'"),
}


def main() -> None:
    items = json.loads(Path("logs/gold_candidates.json").read_text())
    assert len(items) == len(LABELS), f"{len(items)} items vs {len(LABELS)} labels"
    labels_out = {}
    md, flagged_md = ["# Gold set (Fable-adjudicated, frozen)\n",
                      "One label per recipient, by mission text only.\n"], [
        "# Gold set — FLAGGED cases for human audit\n",
        "Uncertain calls: faith-community culture/advocacy, faith-named-but-"
        "secular-mission, thin text, interfaith/academic edges.\n"]
    counts: dict[str, int] = {}
    for i, it in enumerate(items):
        code, flag, reason = LABELS[i]
        label = CODE[code]
        counts[label] = counts.get(label, 0) + 1
        labels_out[it["entity_id"]] = {
            "label": label, "flagged": bool(flag), "reason": reason,
            "name": it["name"], "stratum": it["stratum_hint"],
        }
        line = (f"- **{label}**{' ⚑' if flag else ''} | {it['name']} | "
                f"{reason}\n  > {' '.join((it['mission_text'] or '').split())[:240]}\n")
        md.append(line)
        if flag:
            flagged_md.append(line)
    Path("logs/gold_labels.json").write_text(json.dumps(labels_out, indent=1))
    Path("logs/gold_set.md").write_text("".join(md))
    Path("logs/gold_set_flagged.md").write_text("".join(flagged_md))
    flagged = sum(1 for v in labels_out.values() if v["flagged"])
    print(f"gold set: {len(labels_out)} labels, {flagged} flagged")
    print("distribution:", dict(sorted(counts.items(), key=lambda x: -x[1])))


if __name__ == "__main__":
    main()
